#!/usr/bin/env python 

#import socket module
import socket




# Leaving host as empty string, tells bind() to fill in current machine.
host = ''

# Anything large we don't think is being used
port = 8005

backlog = 5
BufferSize = 1024



# Creates a socket object that will use TCP and IPV4
s = socket.socket(socket.AF_INET, socekt.SOCK_STREAM)

"""
Binds the socket to the host and port
This allows our application to accept incoming connections 
to our destination our host address and port.
This call will fail if some other application is already using this port
on the same machine
"""

s.bind((host,port))

"""
Tells the OS to keep a backlog of five connections.
This means at most five connections waiting while the server is 
handling the current client. We can set this higher, but OS
will typically allow only 5 max.
"""

s.listen(backlog)

"""
infinite while loop accepts a client, reads messag than echos 
it traceback

accept() accepts client connection. Returns client, which is new socket object
											address, address of the client.
recv() takes max amount of data in bytes. 
send() sends data to client.
close() close the socket.


"""

while 1: 
    client, address = s.accept()  
    data = client.recv(BufferSize) 
    if data: 
        client.send(data) 
    client.close()

